"""
Django settings for drf project (Locket).

Generated by 'django-admin startproject' using Django 4.2.

Quy ước:
- Mọi giá trị phụ thuộc môi trường đọc qua các helper env_* ở đầu file, có
  default an toàn, KHÔNG dùng int()/str() trực tiếp lên os.getenv (None hoặc
  chuỗi rỗng sẽ làm nổ ngay lúc import settings).
- base.py chỉ chứa cấu hình chung; development.py / production.py ghi đè phần khác nhau.
- Không import SDK bên ngoài (cloudinary, ...) ở đây: cloudinary/__init__.py đọc
  django.conf.settings ngay lúc import, tức là giữa lúc chính file này đang được nạp.

https://docs.djangoproject.com/en/4.2/topics/settings/
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# drf/ (chứa manage.py). File này nằm ở drf/config/settings/base.py -> lên 3 cấp.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# ---------------------------------------------------------------------------
# Helper đọc biến môi trường
# ---------------------------------------------------------------------------
def env_str(name, default=""):
    value = os.getenv(name)
    if value is None:
        return default
    value = value.strip()
    return value if value else default


def env_bool(name, default=False):
    value = env_str(name)
    if not value:
        return default
    return value.lower() in ("1", "true", "yes", "on")


def env_int(name, default):
    value = env_str(name)
    if not value:
        return default
    try:
        return int(value)
    except ValueError as exc:
        raise ValueError(f"Biến môi trường {name} phải là số nguyên, nhận được {value!r}") from exc


def env_list(name, default=()):
    """Đọc danh sách cách nhau bằng dấu phẩy, bỏ phần tử rỗng."""
    value = env_str(name)
    items = [item.strip() for item in value.split(",")] if value else []
    return [item for item in items if item] or list(default)


# ---------------------------------------------------------------------------
# Core
# ---------------------------------------------------------------------------
# production.py bắt buộc phải có giá trị thật; development.py có fallback insecure.
SECRET_KEY = env_str("SECRET_KEY")

DEBUG = env_bool("DEBUG", False)

# Chấp nhận ALLOWED_HOSTS="a.com,b.com" (mới) hoặc ALLOWED_HOST="a.com" (cũ).
ALLOWED_HOSTS = env_list("ALLOWED_HOSTS") or env_list("ALLOWED_HOST")

SITE_ID = env_int("SITE_ID", 1)

# Tên đường dẫn đăng nhập thật của app (không phải /accounts/login/ mặc định của Django).
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


# ---------------------------------------------------------------------------
# Application definition
# ---------------------------------------------------------------------------
INSTALLED_APPS = [
    "daphne",
    "cloudinary_storage",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "apps.bio",
    "apps.chat",
    "apps.image_share",
    "apps.core",
    "apps.forgot_password",
    "channels",
    "cloudinary",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "config.asgi.application"
WSGI_APPLICATION = "config.wsgi.application"


# ---------------------------------------------------------------------------
# Auth / allauth
# ---------------------------------------------------------------------------
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_QUERY_EMAIL = True
# allauth khuyến cáo tắt: GET tự động đăng nhập là vector CSRF (login CSRF).
SOCIALACCOUNT_LOGIN_ON_GET = False
SOCIALACCOUNT_ADAPTER = "apps.core.adapters.MySocialAccountAdapter"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": env_str("GOOGLE_CLIENT_ID"),
            "secret": env_str("GOOGLE_CLIENT_SECRET"),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}

# BCrypt đứng đầu -> gói `bcrypt` bắt buộc có trong requirements.txt.
# Argon2 đã bỏ vì chưa bao giờ cài argon2-cffi (không có hash argon2 nào trong DB).
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ---------------------------------------------------------------------------
# Email
# ---------------------------------------------------------------------------
EMAIL_BACKEND = env_str("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env_str("EMAIL_HOST", "localhost")
EMAIL_PORT = env_int("EMAIL_PORT", 587)
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
EMAIL_HOST_USER = env_str("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env_str("EMAIL_HOST_PASSWORD")
EMAIL_TIMEOUT = 10
DEFAULT_FROM_EMAIL = env_str("DEFAULT_FROM_EMAIL") or EMAIL_HOST_USER or "webmaster@localhost"


# ---------------------------------------------------------------------------
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# ---------------------------------------------------------------------------
DATABASE_URL = env_str("DATABASE_URL")
if DATABASE_URL:
    _is_postgres = DATABASE_URL.startswith(("postgres://", "postgresql://", "pgsql://"))
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            # sslmode=require chỉ có nghĩa với Postgres; sqlite3.connect() sẽ nổ nếu nhận tham số này.
            ssl_require=env_bool("DATABASE_SSL_REQUIRE", _is_postgres),
        )
    }
else:
    # Không có DATABASE_URL -> sqlite cục bộ (dev/test/CI).
    # production.py bật system check bắt buộc DATABASE_URL (apps/core/checks.py).
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------------------------------------------------------
# Channels / cache
# ---------------------------------------------------------------------------
REDIS_URL = env_str("REDIS_URL") or env_str("REDIS_HOST_URL")
if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        }
    }
else:
    # Chỉ dùng cho dev/test: mọi kết nối phải nằm trong cùng một process.
    CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}

# django-ratelimit dùng cache mặc định. LocMem đúng khi chạy 1 process (1 container daphne);
# nếu scale nhiều replica thì chuyển sang django.core.cache.backends.redis.RedisCache.
CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}


# ---------------------------------------------------------------------------
# Static / media
# ---------------------------------------------------------------------------
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

CLOUDINARY_CLOUD_NAME = env_str("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = env_str("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET = env_str("CLOUDINARY_API_SECRET")
USE_CLOUDINARY = bool(CLOUDINARY_CLOUD_NAME and CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET)

if USE_CLOUDINARY:
    CLOUDINARY_STORAGE = {
        "CLOUD_NAME": CLOUDINARY_CLOUD_NAME,
        "API_KEY": CLOUDINARY_API_KEY,
        "API_SECRET": CLOUDINARY_API_SECRET,
    }

STORAGES = {
    "default": {
        "BACKEND": (
            "cloudinary_storage.storage.MediaCloudinaryStorage"
            if USE_CLOUDINARY
            else "django.core.files.storage.FileSystemStorage"
        )
    },
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}


# ---------------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------------
LANGUAGE_CODE = "vi"
TIME_ZONE = "Asia/Ho_Chi_Minh"
USE_I18N = True
USE_TZ = True


# ---------------------------------------------------------------------------
# Logging: luôn in ra stdout để container/CI nhìn thấy traceback.
# ---------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "%(asctime)s %(levelname)s %(name)s: %(message)s"},
    },
    "handlers": {"console": {"class": "logging.StreamHandler", "formatter": "simple"}},
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "django.request": {"handlers": ["console"], "level": "ERROR", "propagate": False},
        "django.security": {"handlers": ["console"], "level": "WARNING", "propagate": False},
    },
}
