# Generated by Django 4.2.30 on 2026-08-22 04:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_share', '0001_initial'),
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user1_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('user2_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_as_user1', to='bio.bio')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_as_user2', to='bio.bio')),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_at_chat_room', to='chat.chatroom')),
                ('image_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_message_reply', to='image_share.image')),
                ('message_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_message_reply', to='chat.messages')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sender', to='bio.bio')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['chatroom', '-created_at'], name='chat_msg_room_created_idx')],
            },
        ),
    ]
